# import requests
# r = requests.get("https://opentdb.com/api.php?amount=50&type=boolean")
# print(r.results)
question_data = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "Japan was part of the Allied Powers during World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The first computer bug was formed by faulty wires.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The Kingdom of Prussia briefly held land in Estonia.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There is a city called Rome in every continent on Earth.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
                  "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
                  "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "When BMW was established in 1916, it was producing automobiles.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits are rodents.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "St. Louis is the capital of the US State Missouri.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Windows 7 operating system has six main editions.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The USS Missouri (BB-63) last served in the Korean War.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                  "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
                  "question": "The song Scatman&#039;s World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Sound can travel through a vacuum.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "There are a total of 20 races in Formula One 2016 season.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
                  "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}
 ]
